### ISSUE TITLE
[Bug]: Covers not showing for albums added after update

### ISSUE THREAD

**Issue by Faeb35** [kagemomiji/airsonic-advanced#392]
### What happened?

I'm using Sonixd (https://github.com/jeffvli/sonixd) with Airsonic. I stuck on a release from about 9 month ago and finally managed to update to the newer release ([Edge Release 11.1.4-SNAPSHOT.20240303215137](https://github.com/kagemomiji/airsonic-advanced/releases/tag/11.1.4-SNAPSHOT.20240303215137)).

Since I updated I realized that in Sonixd covers of albums added after the upgrade are missing. I also tried with Supersonic client and I faced the same issue.
When I open the Airsonic website everything is fine. Also when playing an album the cover is loaded and showing perfectly. 

I already checked the logs and couldn't find any issue. Also having a look at the reverse proxy logs doesn't show anything obvious. I also tried to rerun the requests for covers from the reverse proxy logs in a browser and they all worked fine.

Sonixd
![grafik](https://github.com/kagemomiji/airsonic-advanced/assets/9485516/9f27b701-f174-4aa0-a50e-d8e72f09c008)

Supersonic
![grafik](https://github.com/kagemomiji/airsonic-advanced/assets/9485516/1e5deb8d-20d6-4a5e-9118-37ee10655c1b)

Since the issue occurs with Sonixd and Supersonic I suspect that it's related to a change in Airsonic.

### Steps to reproduce

1. Update to Edge Release 11.1.4-SNAPSHOT.20240303215137
2. Install Sonixd or Supersonic
3. Show recently added albums

### Version

11.1.x (Edge)

### Version Detail

Edge Release 11.1.4-SNAPSHOT.20240303215137

### Operating System

Windows Server 2022 (21H2)

### Java Version

openjdk version "20.0.1" 2023-04-18

### Database

Other

### DB Detail

Default HSQLDB

### Configuration paramter

JWTKey=XXXXXXX
SettingsChanged=1709283431404
GettingStartedEnabled=false
PodcastUpdateInterval=168
PodcastEpisodeRetentionCount=10
PodcastEpisodeDownloadCount=-1
PodcastFolder=\\XXXXXXXXX\Podcasts
IndexString=A \u00C4 B C D E F G H I J K L M N O \u00D6 P Q R S T U \u00DC V W X-Z(XYZ)
IgnoredArticles=The Tha El La Los Las Le
Shortcuts=New Incoming Podcast
PlaylistFolder=c:\playlists
MusicFileTypes=mp3 ogg oga aac m4a m4b flac wav wma aif aiff ape mpc shn mka opus
VideoFileTypes=flv avi mpg mpeg mp4 m4v mkv mov wmv ogv divx m2ts webm
CoverArtFileTypes2=cover.jpg cover.png cover.gif covers.jpg covers.png folder.jpg jpg jpeg gif png
SortAlbumsByYear=true
WelcomeTitle=
WelcomeSubtitle=
WelcomeMessage2=
LoginMessage=
Theme=default
LocaleLanguage=en
LocaleCountry=
LocaleVariant=
IndexCreationInterval=1
IndexCreationHour=2
FastCacheEnabled=false
OrganizeByFolderStructure=true
ExcludePattern=
IgnoreSymLinks=false
DownloadBitrateLimit=0
UploadBitrateLimit=0
LdapEnabled=false
LdapUrl=ldap://host.domain.com:389/cn=Users,dc=domain,dc=com
LdapSearchFilter=(sAMAccountName={0})
LdapManagerDn=
LdapAutoShadowing=false
SmtpServer=localhost
SmtpEncryption=None
SmtpPort=25
SmtpUser=
SmtpFrom=XXXXXXX
CaptchaEnabled=false
ReCaptchaSiteKey=XXXXXXX
FullScanOnce=false
CoverArtSource=TAGFILE
HlsCommand3=ffmpeg -ss %o -t %d -i %s -async 1 -b:v %bk -s %wx%h -ar 44100 -ac 2 -v 0 -f mpegts -c:v libx264 -preset superfast -c:a libmp3lame -threads 0 -
spring.liquibase.parameters.defaultPodcastFolder=\\XXXXXXXXX\Podcasts
EncryptionKeyPassword=XXXXX
EncryptionKeySalt=XXXX
UploadsFolder=%{['USER_MUSIC_FOLDERS'][0]}/Incoming
EnableCueIndexing=false
HideIndexedFiles=false
FullScan=false
ClearFullScanSettingAfterScan=false
spring.liquibase.parameters.mysqlVarcharLimit=384
DbBackupUpdateInterval=168
DbBackupRetentionCount=3

### Proxy Server

IIS

### client detail

Sonixd & Supersonic

### language

None

### Relevant log output

```console
None
```

**Comment by jr1234jr** [comment]
seems to be the same for several clients, see Q&A #372

**Comment by Faeb35** [comment]
I think I found something supicious when having a look at the API answer for the following call:
`/rest/getAlbumList2.view?type=newest&size=500&offset=0&musicFolderId=0&u=XXXX&s=XXXX&t=9a5e19e17e1addca5db75f333db6f6de&v=1.13.0&c=sonixd&f=json`

For the older albums where cover is showing the JSON looks like this:

```
{
    "id": "18",
    "name": "XX",
    "artist": "XX",
    "artistId": "0",
    "coverArt": "al-18",
    "songCount": 14,
    "duration": 2819,
    "created": "2023-12-30T16:13:36.254Z",
    "year": 2013,
    "genre": "XXX"
}
```

However for the newer albums, where cover art is missing it looks like this:

```
{
    "id": "67327",
    "name": "XX",
    "artist": "XX",
    "artistId": "1527",
    "songCount": 19,
    "duration": 4032,
    "created": "2024-03-06T13:45:45.850Z",
    "year": 2006,
    "genre": "XXX"
}
```

So the coverArt-property is missing in the JSON.

**Comment by maDzGG** [comment]
This happened to me too. 

I am on latest snapshot + tried downgrading. No luck. 

I use substreamer for iOS
Airsonic on ubuntu 20.04
Default DB

**Comment by kagemomiji** [comment]
@maDzGG @Faeb35 
I have fixed the WAR file and Docker image. Could you please test whichever you prefer?
Please scan library before try the API.

war file [zip](https://github.com/kagemomiji/airsonic-advanced/actions/runs/8233919363/artifacts/1315066737)
docker image: ghcr.io/kagemomiji/airsonic-advanced:pr-395

**Comment by maDzGG** [comment]
> @maDzGG @Faeb35 I have fixed the WAR file and Docker image. Could you please test whichever you prefer? Please scan library before try the API.
> 
> war file [zip](https://github.com/kagemomiji/airsonic-advanced/actions/runs/8233919363/artifacts/1315066737) docker image: ghcr.io/kagemomiji/airsonic-advanced:pr-395

You rock. It's working again. Thank you so much!

**Comment by cheskykay** [comment]
now playing screen on apps still don't get updated images. tried on dsub and subsonic on android

**Comment by Faeb35** [comment]
@kagemomiji You are the best!! That fixed the issue for me with Sonixd, thank you so much!

**Comment by kagemomiji** [comment]
@cheskykay 
Please check if a library scan has been done or if clearing the cache makes no difference.

**Comment by cheskykay** [comment]
a full Scan has been done and the cache has been cleared. 
it's a huge DB 
69,684 songs
617.39 GB

on substreamer app i still have that the images dont load on the front tile page. but now playing is correct when it does have a image. 

on dsub and subsonic grid and list are mostly good. now playing is always the first image that was played after cache clearing.

**Comment by Faeb35** [comment]
@cheskykay do you have the chance to install these apps on another device to see if you get the same behavior?

**Comment by kagemomiji** [comment]
@cheskykay 
I've tried the Substreamer Android app and confirmed that album cover art does not appear. 
However, Substreamer's source code and other details are not made public, so it's unclear how it attempts to fetch cover art, making it difficult to devise a fix. 

Upon reviewing the API request logs, there appears to be no access to the CoverArt fetching API, leading me to believe there is a compatibility issue between Substreamer's CoverArt retrieval function and the Airsonic Advanced API. 

However, I have verified that the Substreamer web app (docker) does display cover art on the top page for those that have it (although it couldn't be fetched in the album list).

Considering this issue has been resolved with Sonixd and DSub, I propose considering a separate issue to address compatibility with Substreamer.

**Comment by cheskykay** [comment]
Tried reinstall for dsub and dsub beta android apps and didn't help. For my
server with the last war file here.

The demo server did work



Subsonic android app also didn't work

Ultrasonic android app works fine.

All referring to the now playing section.

You can can close from my end. Just spotted it and saw this ticket and felt
that it can be fixed.

**Comment by dsiminiuk** [comment]
THANK YOU! THANK YOU! THANK YOU!

I've complained numerous times over the years from Subsonic to Airsomic and now it is fixed!

Made my day!
